

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  dns:
    image: ubuntu/bind9:latest
    container_name: dns
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zones:/etc/bind/zones
    networks:
      - webnet

  www:
    image: nginx:latest
    container_name: www
    volumes:
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/html:/usr/share/nginx/html
    networks:
      - webnet

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.mary.asa.br
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp://mail.mary.asa.br
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
    networks:
      - webnet
    volumes:
      - ./roundcube/config.inc.php:/var/www/html/config/config.inc.php
      - ./roundcube/db:/var/roundcube/db

  mail:
    image: boky/postfix:latest
    container_name: mail
    environment:
      - MAILNAME=mary.asa.br
      - SMTP_SERVER=smtp.mary.asa.br
      - RELAY_NETWORKS=:192.168.0.0/24
      - LOG_LEVEL=debug
      - HOSTNAME=mary.asa.br
      - SMTP_HOSTNAME=mail.mary.asa.br
      - ALLOWED_SENDER_DOMAINS=*:mary.asa.br
    networks:
      - webnet
    volumes:
      - ./mail/postfix/main.cf:/etc/postfix/main.cf
      - maildata:/var/mail
    ports:
      - "143:143"
      
    command: sh -c "mkdir -p /var/spool/postfix/private/ && chown -R postfix:postfix /var/spool/postfix && postfix start-fg"

  dovecot:
    build: ./mail/dovecot
    container_name: dovecot
    networks:
      - webnet
    volumes:
      - ./mail/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - maildata:/var/mail

volumes:
  maildata:

networks:
  webnet:
    driver: bridge
